#!/usr/bin/env bash
# Installs, configures, and starts the server
# Imanol Asolo

sudo apt-get update -y
sudo apt-get install nginx -y
echo 'server{
listen 80;
{ / location
	rot /var/www/html;
	index inxex.html;
}
}' > /etc/nginx/sites-available/default
echo "Hello World" > /var/www/html/index.html
sudo service nginx restart
