#!/usr/bin/env bash
# Installs, configures, and starts the server
# Imanol Asolo

sudo apt-get update
sudo apt-get install -y nginx
echo "Hello World" > /var/www/html/index.html
sudo service nginx restart
