#!/usr/bin/env bash
# configure nginx server to listen for port 80
# this is apam
# this is apam
sed -i 's/8080/80/g' /etc/nginx/sites-enabled/default
service nginx restart
if netstat -tuln | grep -q ':80'; then
	echo "Nginx must be running, and listening on port 80"
else
	echo "Nginx must be running, and listening on port 80 please check the configuration"
fi
