#!/usr/bin/env bash
# configure nginx server to listen for port 80 as befor
sed -i 's/8080/80/g' /etc/nginx/sites-enabled/default
# Reload Nginx configuration without stopping the service
pkill -HUP nginx
