#!/usr/bin/env bash
# changes the following domin resolve ips
# localhost form 127.0.0.1 to 127.0.0.2
# facebook.com from 157.240.11.35 to 8.8.8.8

sudo cp /etc/hosts /etc/hosts.bak

sudo sed -i '/^127\.0\.0\.1\s\+localhost/d' /etc/hosts
echo '127.0.0.2 localhost' | sudo tee -a /etc/hosts
sudo sed -i '/^/*facebook\.com/' /etc/hosts
echo '8.8.8.8 facebook.com' | sudo tee -a /etc/hosts
echo "the /etc/hosts file has been updated. Here ar the new entries:"
grep 'localhost\|facebook.com' /etc/hosts
